### ISSUE TITLE
Editor features

### ISSUE THREAD

**Issue by jkazimierczak** [rphlmr/drizzle-run#25]
First of all, thanks for this app - it helped me troubleshoot my relation definitions. The visualizer is just super-duper helpful. ❤️ 

The whole looks very aesthetic, but it steals a bit from the usability of the editor, namely:
- [ ] Line numbers - this could be useful for longer schemas,
- [ ] Editor scrollbars are missing - having to use mousewheel to go back and forth is a bit painful, especially for scrolling longer files,
- [ ] Scroll position is not kept when switching between files.

These are minor things, but affect the experience of using the playground. I used it by pasting the whole schema (which is quite long) and then started narrowing down to just necessary tables, but working with such long file was a bit confusing and cumbersome without these features.

**Comment by rphlmr** [comment]
👋 It's now live! https://github.com/rphlmr/drizzle-run/releases/tag/v0.9.0
