### ISSUE TITLE
Bug: Clicking on the profile picture errors

### ISSUE THREAD

**Issue by jkazimierczak** [rphlmr/drizzle-run#26]
Hi! Thanks for handling #25! It seems that while the upgrades ocurred, another bug has appeared too - clicking on the profile picture results in:

```
`DialogTrigger` must be used within `Dialog`
```

Also, I guess that the text in `` ` `` was meant to be rendered in `<pre>` tags, which doesn't work also.

**Comment by rphlmr** [comment]
Oups, sorry for this issue. Should be fixed now!
Thanks
